name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add cargo target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Install linker
      run: sudo apt update && sudo apt install mingw-w64
    - name: Build
      run: cargo build --verbose --target x86_64-pc-windows-gnu --release
